// fuzz_secrets.cpp — libFuzzer entry point for the discovery engine.
// Feeds fuzzer-generated bytes into the content engine (M2/M3), the JSON reader,
// and the SBOM package-DB parsers (M4), exercising every bounds-checked matcher
// and validator on adversarial input. "Fuzz the parsers from day one."
//
// Build (from the mithril dir):
//   clang++ -std=c++20 -O1 -g -fsanitize=fuzzer,address -I src \
//     src/ahocorasick.cpp src/validators.cpp src/rules_builtin.cpp src/engine.cpp \
//     src/sbom.cpp fuzz/fuzz_secrets.cpp -o fuzz/fuzz_secrets
// Run: ./fuzz/fuzz_secrets -max_total_time=60
#include <cstddef>
#include <cstdint>
#include <span>
#include <string_view>

#include "binver.hpp"
#include "credstore.hpp"
#include "engine.hpp"
#include "filever.hpp"
#include "inflate.hpp"
#include "jsonparse.hpp"
#include "kconfig.hpp"
#include "langmanifest.hpp"
#include "license.hpp"
#include "reader.hpp"
#include "rpm.hpp"
#include "rules_builtin.hpp"
#include "sbom.hpp"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    static const ft::Engine engine(ft::builtin_content_rules(), ft::builtin_path_rules());
    std::span<const uint8_t> bytes(data, size);

    ft::Reader reader(bytes);
    auto findings = engine.scan_content(reader);
    (void)findings;

    auto j = ft::json_parse(std::string_view(reinterpret_cast<const char*>(data), size));
    (void)j;

    auto d1 = ft::parse_deb822_status(bytes, "dpkg", "status");
    auto d2 = ft::parse_apk_installed(bytes, "installed");
    auto d3 = ft::parse_shadow(bytes, "shadow");
    auto d4 = ft::parse_htpasswd(bytes, "htpasswd");
    auto d5 = ft::scan_binver(bytes, "prog");
    auto d6 = ft::scan_licenses("COPYING", bytes);
    auto d7 = ft::scan_langmanifest("package-lock.json", bytes);
    auto d8 = ft::parse_rpm_db(bytes, "var/lib/rpm/Packages");
    auto d9 = ft::scan_filename_version("lib/libuClibc-0.9.33.so");
    auto d10 = ft::scan_kernel_version(bytes, "kernel");
    auto d11 = ft::gzip_inflate(bytes);
    auto d12 = ft::inflate_raw(bytes);
    auto d13 = ft::scan_kconfig("k", bytes);
    (void)d1;
    (void)d2;
    (void)d3;
    (void)d4;
    (void)d5;
    (void)d6;
    (void)d7;
    (void)d8;
    (void)d9;
    (void)d10;
    (void)d11;
    (void)d12;
    (void)d13;
    return 0;
}
