#!/usr/bin/env python3
"""Regenerate the boot-key reference corpus from the vendored public sources.

Reads data/bootkeys/ (public keys and certificates only — never private keys)
and emits src/bootkeys_corpus.inc: the compiled-in constexpr tables that
bootkeys.cpp matches against. The corpus is baked into the binary (mithril makes
no network call and reads no external table at scan time); this generator only
runs at authoring time to keep the tables reproducible and auditable from source.

Pure standard library (hashlib + a tiny DER walk); needs no openssl/avbtool.

Sources (all public):
  aosp-avb/*.avbpubkey   AVB public-key blobs (avbtool extract_public_key) of the
                         AOSP test keys, external/avb/test/data/testkey_rsa*.pem.
                         Fingerprint = SHA-256 of the blob (what the AVB pass hashes).
  aosp-signing/*.x509.pem  AOSP APK/OTA signing test certs,
                         build/make target/product/security/*.x509.pem.
                         Fingerprint = SHA-256 of the DER cert.
  pkfail/*.p7            CERT/CC PKfail (VU#455367) AMI "DO NOT TRUST" test PK,
                         PKCS#7 carrying the cert. Fingerprint = SHA-256 of the cert.

Usage: python3 tools/gen_bootkeys.py            # writes src/bootkeys_corpus.inc
       python3 tools/gen_bootkeys.py --check     # verify the .inc is up to date
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data", "bootkeys")
OUT = os.path.join(ROOT, "src", "bootkeys_corpus.inc")

FP_LEN = 32  # first 32 lowercase hex chars of SHA-256 (matches bootkeys.cpp)


def fp(data):
    return hashlib.sha256(data).hexdigest()[:FP_LEN]


# --- minimal DER ---
def tlv(d, i):
    tag = d[i]; j = i + 1; ln = d[j]; j += 1
    if ln & 0x80:
        n = ln & 0x7F; ln = int.from_bytes(d[j:j + n], "big"); j += n
    return tag, j, ln, j + ln  # tag, content_start, length, end


def pem_to_der(pem_bytes):
    import base64
    b = pem_bytes.decode("latin1")
    lines = [ln for ln in b.splitlines() if ln and "-----" not in ln]
    return base64.b64decode("".join(lines))


def cert_from_pkcs7(d):
    """First X.509 certificate in a DER PKCS#7 SignedData."""
    _, cs, _, e = tlv(d, 0)     # outer SEQUENCE
    i = cs
    while i < e:
        tag, c, _, end = tlv(d, i)
        if tag == 0xA0:          # certificates [0] IMPLICIT
            ct, _, _, ce = tlv(d, c)
            if ct == 0x30:
                return d[c:ce]
        i = end
    return None


def read(*parts):
    with open(os.path.join(DATA, *parts), "rb") as f:
        return f.read()


def collect():
    avb, certs = [], []
    d = os.path.join(DATA, "aosp-avb")
    for name in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        bits = "".join(ch for ch in name if ch.isdigit()) or "?"
        avb.append((fp(read("aosp-avb", name)),
                    "AOSP AVB test key (RSA-%s)" % bits,
                    "AOSP external/avb/test/data/%s.pem" % os.path.splitext(name)[0]))
    d = os.path.join(DATA, "aosp-signing")
    for name in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        base = os.path.splitext(os.path.splitext(name)[0])[0]  # strip .x509.pem
        certs.append((fp(pem_to_der(read("aosp-signing", name))),
                      "AOSP %s signing test cert" % base,
                      "AOSP build/make .../security/%s.x509.pem" % base))
    d = os.path.join(DATA, "pkfail")
    for name in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        cert = cert_from_pkcs7(read("pkfail", name))
        if cert:
            certs.append((fp(cert),
                          "AMI 'DO NOT TRUST' test PK (PKfail, %s)" % os.path.splitext(name)[0],
                          "CERT/CC PKfail VU#455367 (%s)" % name))
    return avb, certs


def emit(avb, certs):
    def rows(entries):
        return "".join('    {"%s", "%s", "%s"},\n' % (f, l.replace('"', '\\"'), r) for f, l, r in entries)
    o = "// GENERATED by tools/gen_bootkeys.py from data/bootkeys/ — do not edit by hand.\n"
    o += "// Compiled-in reference corpus; regenerate after changing the vendored sources.\n\n"
    o += "// AVB public-key-blob fingerprints (SHA-256[0:32] of the AVB pubkey blob).\n"
    o += "inline constexpr KnownKey kAvbKeys[] = {\n" + rows(avb) + "};\n\n"
    o += "// X.509 certificate fingerprints (SHA-256[0:32] of the DER cert).\n"
    o += "inline constexpr KnownKey kCerts[] = {\n" + rows(certs) + "};\n"
    return o


def main():
    avb, certs = collect()
    text = emit(avb, certs)
    if "--check" in sys.argv:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            print("bootkeys_corpus.inc is STALE; run tools/gen_bootkeys.py", file=sys.stderr)
            return 1
        print("bootkeys_corpus.inc is up to date (%d AVB, %d certs)" % (len(avb), len(certs)))
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote %s (%d AVB keys, %d certs)" % (OUT, len(avb), len(certs)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
