// keyweak.hpp — offline weakness checks on a recovered public key.
//
// The generation-failure half of the key-weakness pass (the disclosure half is
// keycorpus.hpp). Everything here is computed from the public key alone, fully
// offline, no multiprecision arithmetic:
//
//   ROCA (CVE-2017-15361) — Infineon RSALib structured primes. The Coppersmith
//     factorization itself needs bignum (Phase 2), but the *fingerprint* that
//     says a modulus is vulnerable needs only (n mod small_prime): for each of a
//     fixed set of small primes, n mod p must land in the multiplicative subgroup
//     generated by 65537 mod p. One prime whose residue is outside its subgroup
//     proves the key is NOT ROCA; all inside is the ROCA fingerprint.
//
//   Structural — undersized modulus, broken/again-small exponent, even modulus.
//
// The modulus arrives big-endian (pubkey.hpp). `n mod p` is byte-wise long
// division by a machine word; no bignum type is introduced.
#pragma once

#include <cstdint>
#include <span>
#include <string>
#include <vector>

namespace ft {

// n mod m for a big-endian modulus n and a machine-word m (m must be nonzero).
uint64_t mod_be(std::span<const uint8_t> n_be, uint64_t m);

// True if the RSA modulus carries the ROCA (CVE-2017-15361) fingerprint. A false
// return is a proof of non-vulnerability; a true return is the fingerprint the
// CRoCS detector uses (a Coppersmith attack then recovers the private key).
bool is_roca(std::span<const uint8_t> n_be);

// The ROCA small-prime fingerprint masks, exposed for the unit test: for prime
// primes()[i], mask()[i] has bit r set iff r is in the subgroup <65537> mod p.
// These reproduce the published CRoCS `prints` table by construction.
std::span<const uint32_t> roca_primes();
uint64_t roca_mask_for(uint32_t prime);  // bit r set == r reachable as 65537^k mod prime

// A structural weakness computable from the public key with no factoring.
struct KeyWeakness {
    std::string id;    // finding type, e.g. "rsa-undersized"
    std::string sev;   // "high" / "medium" / "info"
    std::string why;   // one-line reason (human)
    std::string cwe;   // e.g. "CWE-326"
};

// Structural weaknesses of an RSA key (modulus bit size + exponent). `bits` is the
// modulus bit length; `e_be` the public exponent big-endian (may be large, so it
// is not a uint64 — a large exponent is normal, not a weakness).
std::vector<KeyWeakness> rsa_structural_weaknesses(size_t bits, std::span<const uint8_t> e_be,
                                                   std::span<const uint8_t> n_be);

// ---- Phase 2: factoring-based recovery (uses the in-tree bignum) ----------

// Fermat close-prime factorization. If the modulus n = p*q with |p-q| small
// enough to reach within `max_steps` of ceil(sqrt(n)), returns true and sets
// p_be/q_be (p <= q), the recovered factors. Bounded work; a false return only
// means "not found within the window", not "prime". Catches the bad-RNG /
// twin-prime generation class (e.g. CVE-2022-26320-style shared-high-bits keys).
bool fermat_factor(std::span<const uint8_t> n_be, std::vector<uint8_t>& p_be,
                   std::vector<uint8_t>& q_be, unsigned max_steps = 100);

// Wiener small-private-exponent attack. If the RSA private exponent d is small
// (roughly d < n^0.25 / 3, which forces a large public exponent e), recovers it
// from (n, e); returns true and sets d_be. Cheap to reject: only meaningful when
// e is large relative to n, so the caller may skip it for the common e=65537.
bool wiener_attack(std::span<const uint8_t> n_be, std::span<const uint8_t> e_be,
                   std::vector<uint8_t>& d_be);

// gcd of two big-endian moduli (for the cross-image batch-GCD shared-prime check).
// Returns the gcd as big-endian bytes; a result strictly between 1 and each input
// is a shared prime factor -> both moduli are factorable.
std::vector<uint8_t> modulus_gcd(std::span<const uint8_t> a_be, std::span<const uint8_t> b_be);

}  // namespace ft
