// keyweak.cpp — offline public-key weakness checks. See keyweak.hpp.
#include "keyweak.hpp"

#include <array>

#include "bigint.hpp"

namespace ft {

namespace {

// The ROCA small primes (3..167), exactly the set the CRoCS detector uses. n mod
// p_i must land in the subgroup generated by 65537 mod p_i for every p_i.
constexpr std::array<uint32_t, 38> kRocaPrimes = {
    3,  5,  7,  11, 13, 17, 19, 23, 29, 31,  37,  41,  43,
    47, 53, 59, 61, 67, 71, 73, 79, 83, 89,  97,  101, 103,
    107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167};

// mask[i] bit r set == r is reachable as 65537^k mod kRocaPrimes[i]. Computed once
// from the 65537 subgroup; this reproduces the published `prints` constants (the
// unit test pins the first several against known values). Every prime is < 256 so
// its residue set fits in the low bits; the widest (167) needs 167 bits, so the
// mask is a small bitset of 64-bit words.
struct Masks {
    // 167 bits -> 3 words per prime.
    std::array<std::array<uint64_t, 3>, kRocaPrimes.size()> bits{};
    Masks() {
        for (size_t i = 0; i < kRocaPrimes.size(); ++i) {
            const uint64_t p = kRocaPrimes[i];
            uint64_t g = 65537 % p;
            uint64_t r = 1 % p;  // 65537^0
            for (uint64_t k = 0; k < p; ++k) {
                bits[i][r >> 6] |= (uint64_t(1) << (r & 63));
                r = (r * g) % p;
                if (r == (1 % p)) {  // completed the cycle
                    bits[i][r >> 6] |= (uint64_t(1) << (r & 63));
                    break;
                }
            }
        }
    }
    bool has(size_t i, uint64_t r) const { return (bits[i][r >> 6] >> (r & 63)) & 1; }
};

const Masks& masks() {
    static const Masks m;
    return m;
}

}  // namespace

uint64_t mod_be(std::span<const uint8_t> n_be, uint64_t m) {
    uint64_t r = 0;
    // r = (r << 8 | byte) % m, done per byte. m < 2^32 for the ROCA primes, so
    // (r << 8) never overflows a uint64 (r < m <= 2^32, r<<8 < 2^40).
    for (uint8_t b : n_be) r = ((r << 8) | b) % m;
    return r;
}

std::span<const uint32_t> roca_primes() { return {kRocaPrimes.data(), kRocaPrimes.size()}; }

uint64_t roca_mask_for(uint32_t prime) {
    // Low 64 bits of the mask for `prime` (all ROCA primes < 64 fit; the wider
    // primes' low word is what the test's small-prime oracle checks).
    for (size_t i = 0; i < kRocaPrimes.size(); ++i)
        if (kRocaPrimes[i] == prime) return masks().bits[i][0];
    return 0;
}

bool is_roca(std::span<const uint8_t> n_be) {
    if (n_be.empty()) return false;
    const Masks& mk = masks();
    for (size_t i = 0; i < kRocaPrimes.size(); ++i) {
        uint64_t r = mod_be(n_be, kRocaPrimes[i]);
        if (!mk.has(i, r)) return false;  // residue outside the subgroup -> not ROCA
    }
    return true;
}

std::vector<KeyWeakness> rsa_structural_weaknesses(size_t bits, std::span<const uint8_t> e_be,
                                                   std::span<const uint8_t> n_be) {
    std::vector<KeyWeakness> out;

    // Modulus size. NIST/industry floor is 2048; below 1024 is trivially
    // factorable on commodity hardware, 1024 is deprecated, <2048 is weak.
    if (bits > 0 && bits < 1024)
        out.push_back({"rsa-tiny-modulus", "high",
                       "RSA modulus is " + std::to_string(bits) +
                           " bits: factorable on commodity hardware",
                       "CWE-326"});
    else if (bits == 1024 || (bits > 1024 && bits < 2048))
        out.push_back({"rsa-weak-modulus", "medium",
                       "RSA modulus is " + std::to_string(bits) +
                           " bits: below the 2048-bit floor (deprecated)",
                       "CWE-326"});

    // Public exponent, read from the big-endian magnitude (a large e is normal,
    // not a weakness — do not treat "does not fit u64" as zero). e in {0,1} is
    // broken (no encryption); an even exponent is invalid (not coprime to phi).
    bool e_zero = true;
    for (uint8_t b : e_be) if (b) { e_zero = false; break; }
    bool e_one = (e_be.size() == 1 && e_be[0] == 1) ||
                 (!e_be.empty() && e_be.back() == 1 && [&] {
                     for (size_t i = 0; i + 1 < e_be.size(); ++i) if (e_be[i]) return false;
                     return true;
                 }());
    if (e_zero || e_one)
        out.push_back({"rsa-broken-exponent", "high",
                       std::string("RSA public exponent is ") + (e_zero ? "0" : "1") +
                           ": ciphertext equals plaintext (no security)",
                       "CWE-780"});
    else if ((e_be.back() & 1) == 0)
        out.push_back({"rsa-even-exponent", "high",
                       "RSA public exponent is even: not a valid RSA key", "CWE-780"});

    // Even modulus -> shares the factor 2, trivially factorable.
    if (!n_be.empty() && (n_be.back() & 1) == 0)
        out.push_back({"rsa-even-modulus", "high",
                       "RSA modulus is even (divisible by 2): trivially factorable",
                       "CWE-326"});

    return out;
}

bool fermat_factor(std::span<const uint8_t> n_be, std::vector<uint8_t>& p_be,
                   std::vector<uint8_t>& q_be, unsigned max_steps) {
    BigUint N = BigUint::from_be(n_be);
    if (N.is_zero() || !N.is_odd()) return false;  // even modulus handled structurally
    const BigUint one(1);
    // a = ceil(sqrt(N)); track a2 = a*a incrementally ((a+1)^2 = a^2 + 2a + 1).
    BigUint a = N.isqrt();
    if (a * a != N) a = a + one;
    BigUint a2 = a * a;
    for (unsigned i = 0; i < max_steps; ++i) {
        BigUint b2 = a2 - N;  // a >= ceil(sqrt N) so a2 >= N
        BigUint b;
        if (b2.is_perfect_square(&b)) {
            BigUint p = a - b, q = a + b;
            if (p > one && p != N) {  // a genuine nontrivial factorization
                p_be = p.to_be();
                q_be = q.to_be();
                return true;
            }
        }
        a2 = a2 + a.shl_bits(1) + one;  // now (a+1)^2
        a = a + one;
    }
    return false;
}

bool wiener_attack(std::span<const uint8_t> n_be, std::span<const uint8_t> e_be,
                   std::vector<uint8_t>& d_be) {
    BigUint N = BigUint::from_be(n_be);
    BigUint E = BigUint::from_be(e_be);
    if (E.is_zero() || N.is_zero() || E >= N) return false;
    const BigUint one(1), four(4);
    // Continued-fraction convergents of e/N; each denominator k_i is a candidate
    // private exponent d, each numerator h_i a candidate for k in e*d - 1 = k*phi.
    BigUint num = E, den = N;                 // expand e/N
    BigUint h_pp(0), h_p(1), k_pp(1), k_p(0);  // convergent recurrence seeds
    for (size_t iter = 0; iter < N.bit_length() + 4 && !den.is_zero(); ++iter) {
        BigUint a, rem;
        num.divmod(den, a, rem);
        BigUint h = a * h_p + h_pp;   // convergent numerator  (candidate k)
        BigUint k = a * k_p + k_pp;   // convergent denominator (candidate d)
        // Test the convergent: with cand_k = h, cand_d = k, phi = (e*d - 1)/k.
        if (!h.is_zero()) {
            BigUint ed1 = E * k;
            if (ed1 > one) {
                ed1 = ed1 - one;
                BigUint phi, r2;
                ed1.divmod(h, phi, r2);
                if (r2.is_zero() && !phi.is_zero() && phi < N) {
                    // s = p + q = N - phi + 1; discriminant s^2 - 4N a perfect square.
                    BigUint s = (N - phi) + one;
                    BigUint s2 = s * s, fourN = four * N;
                    if (s2 >= fourN && (s2 - fourN).is_perfect_square()) {
                        d_be = k.to_be();
                        return true;
                    }
                }
            }
        }
        h_pp = h_p; h_p = h;
        k_pp = k_p; k_p = k;
        num = den; den = rem;
    }
    return false;
}

std::vector<uint8_t> modulus_gcd(std::span<const uint8_t> a_be, std::span<const uint8_t> b_be) {
    return BigUint::gcd(BigUint::from_be(a_be), BigUint::from_be(b_be)).to_be();
}

}  // namespace ft
